Repository realm/realm-graphql-service, pull requests merged in 2018-09, with the labels that each got.

#74 Fix upgrade handler
  CHANGELOG.md
  src/service.ts
Labels: G:Rangers, T:Bug

#76 Add an option to represent integers as floats in the schema
  CHANGELOG.md
  src/service.ts
Labels: G:Rangers, O:User PE/EE, T:Enhancement

#77 Update CHANGELOG.md
  CHANGELOG.md
Labels: T:Internal
